"""Semantic version increment script for backend/src/version.py."""

import os
import re
from pathlib import Path


def bump_version() -> str:
  """Bumps the patch version in backend/src/version.py."""
  version_file = Path(__file__).parent.parent.parent / "backend" / "src" / "version.py"
  version_file.parent.mkdir(parents=True, exist_ok=True)

  current_version = "0.1.0"
  if version_file.exists():
    content = version_file.read_text(encoding="utf-8")
    match = re.search(r__version__\s*=\s*['](\d+)\.(\d+)\.(\d+)['], content)
    if match:
      major, minor, patch = map(int, match.groups())
      current_version = f"{major}.{minor}.{patch + 1}"
    else:
      current_version = "0.1.1"

  output = f"""# Auto-generated by infra/scripts/increment_version.py
__version__ = "{current_version}"
"""
  version_file.write_text(output, encoding="utf-8")
  print(f"[Version Bump] Updated backend version to: {current_version}")
  return current_version


if __name__ == "__main__":
  bump_version()
